apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
spec:
  selector:
    matchLabels:
      app: capstone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 2
  template:
    metadata:      
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: 815161874902.dkr.ecr.us-west-2.amazonaws.com/udacity-devops:latest
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-deployment
spec:
  type: LoadBalancer
  selector:
    app: capstone
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000      